version = 0.1

[default.deploy.parameters]
stack_name = "whispr-backend"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "OpenAIApiKey=\"${OPENAI_API_KEY}\""
